# Generated by Django 5.2.1 on 2025-05-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='value',
        ),
    ]
